<?php

namespace AppBundle\Repository;

/**
 * NaturPersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NaturPersRepository extends \Doctrine\ORM\EntityRepository
{
}
