<?php

namespace AppBundle\Repository;

/**
 * OrderEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderEventRepository extends \Doctrine\ORM\EntityRepository
{
}
