<?php

namespace AppBundle\Repository;

/**
 * OrderTabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderTabelRepository extends \Doctrine\ORM\EntityRepository
{
}
