<?php

namespace AppBundle\Repository;

/**
 * OrderPayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderPayRepository extends \Doctrine\ORM\EntityRepository
{
}
