<?php

namespace AppBundle\Repository;

/**
 * portfolioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class portfolioRepository extends \Doctrine\ORM\EntityRepository
{
}
