<?php

namespace AppBundle\Repository;

/**
 * SectorObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectorObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
