<?php

namespace AppBundle\Repository;

/**
 * SpecSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
