<?php

namespace AppBundle\Repository;

/**
 * StageOrderEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageOrderEventRepository extends \Doctrine\ORM\EntityRepository
{
}
