<?php

namespace AppBundle\Repository;

/**
 * StageOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
