<?php

namespace AppBundle\Repository;

/**
 * SubObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
