<?php

namespace AppBundle\Repository;

/**
 * SubObjectItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubObjectItemRepository extends \Doctrine\ORM\EntityRepository
{
}
