project:
    path:  /
    defaults: { _controller: "AppBundle:project:index" }

project_show:
    path:  /{id}/show
    defaults: { _controller: "AppBundle:project:show" }
    
project_report_money:
    path:  /{id}/report1
    defaults: { _controller: "AppBundle:project:reportMoney" }    
    
project_statements:
    path:  /{id}/statements
    defaults: { _controller: "AppBundle:project:statements" }     
    requirements: { _method: post|get }
    
project_pays_confirm:
    path:  /{id}/pays-confirm
    defaults: { _controller: "AppBundle:project:paysConfirm" }     
    requirements: { _method: post|get }    
    
project_new:
    path:  /new
    defaults: { _controller: "AppBundle:project:new" }

project_create:
    path:  /create
    defaults: { _controller: "AppBundle:project:create" }
    requirements: { _method: post }

project_edit:
    path:  /{id}/edit
    defaults: { _controller: "AppBundle:project:edit" }

project_update:
    path:  /{id}/update
    defaults: { _controller: "AppBundle:project:update" }
    requirements: { _method: post|put }

project_delete:
    path:  /{id}/delete
    defaults: { _controller: "AppBundle:project:delete" }
    requirements: { _method: post|delete }
    
project_by_id_delete:
    path:  /delete/{id}
    defaults: { _controller: "AppBundle:project:deleteById" }
    requirements: { _method: get }
    

project_bulk_action:
    path:  /bulk-action
    defaults: { _controller: "AppBundle:project:bulk" }
    requirements: { _method: post }
    
