projectstage:
    path:  /
    defaults: { _controller: "AppBundle:ProjectStage:index" }

projectstage_show:
    path:  /{id}/show
    defaults: { _controller: "AppBundle:ProjectStage:show" }

projectstage_new:
    path:  /{proj_id}/new
    defaults: { _controller: AppBundle:ProjectStage:new, proj_id: proj_id }
    requirements:
        _method:  POST
        proj_id: \d+ 

projectstage_create:
    path:  /create
    defaults: { _controller: "AppBundle:ProjectStage:create" }
    requirements: { _method: post }

projectstage_edit:
    path:  /{id}/edit
    defaults: { _controller: "AppBundle:ProjectStage:edit" }

projectstage_update:
    path:  /{id}/update
    defaults: { _controller: "AppBundle:ProjectStage:update" }
    requirements: { _method: post|put }

projectstage_delete:
    path:  /{id}/delete
    defaults: { _controller: "AppBundle:ProjectStage:delete" }
    requirements: { _method: post|delete }
    
projectstage_by_id_delete:
    path:  /delete/{id}
    defaults: { _controller: "AppBundle:ProjectStage:deleteById" }
    requirements: { _method: get }
    

projectstage_bulk_action:
    path:  /bulk-action
    defaults: { _controller: "AppBundle:ProjectStage:bulk" }
    requirements: { _method: post }
    
